### PR TITLE
Hand Controlled Screenshot Opencv

### PR DESCRIPTION
**Pull request by Invincible1602**
Fixes Issue #44,

A Hand Controlled Screenshot feature is created with the help of OpenCV and MediaPipe, enabling users to capture screenshots effortlessly through hand gestures. The implementation provides a unique and interactive way to take screenshots, enhancing user experience.

### CODE REVIEW

**Comment by abhisek247767** [comment]
can you add readme.md file for understand how to use and run your code step by step

**Comment by Invincible1602** [comment]
Sir this is coming in my portal. Sir, can you help me why i am getting this warning in my Hacktoberfest profile.

image

**Comment by abhisek247767** [comment]
Yes... i am looking into if. Already working on that

**Comment by Invincible1602** [comment]
Sir any progress related to this above issue

**Pull request merged**
