### PR TITLE
first frontend commit

### PR DESCRIPTION
**Pull request by shrek-28**
solution to issue #46 

created a basic frontend commit 
1. added a basic hero and features
2. open to adding further frontend features

please add further comments for developments

### CODE REVIEW

**Comment by abhisek247767** [comment]
it's simple frontend page...add some more integration with ML or other AI Techniques such that it's relevant. take an example  yu create page where user upload picture you model predicts and show whether it's male or female something like that

**Comment by shrek-28** [comment]
no, this is just page to host all the projects in the repository. acts as a graphical interface so that people need not navigate through full repo to find a project. improves the reach of the project.

a form to add your project to the repository can be created.

**Comment by abhisek247767** [comment]
can show a demo... do one think. Record a video and share with me...use screen recorder extension or jam...whatever you like and share with me or shared screen shot of that page..It's make sense to better

**Comment by shrek-28** [comment]
https://github.com/user-attachments/assets/d1778d0a-f889-4f85-a9d6-192b200d32d7

This the very very basic version of the page.
The developments I hope to make:
1.  the "featured" projects contain the most viewed projects of the date.
2. add a form to add further projects
3. sort the projects based on algorithms they use and the domain they come under
4. a blog featuring the basics of every domain and ML algorithm

**Comment by abhisek247767** [comment]
That's nice.. Do one thing add demo images on that cart and add url any of project which is in that repository ... attach it in code give me screen shot here and after that commit code. And do more customize design if possible...thats looks good user interface. I hope you do it. I will merge it

good idea.

**Comment by shrek-28** [comment]
sure, will do
a doubt tho:
1. what customize design do you prefer or need for this to improve UI?

**Comment by abhisek247767** [comment]
whatever looks you better..

**Comment by shrek-28** [comment]
could you please add hacktoberfest tag, this is a part of hacktoberfest

**Comment by shrek-28** [comment]
have added dummy images with a link to project as requested, please check. if demo is needed, i will provide.

**Comment by abhisek247767** [comment]
give demo

**Comment by shrek-28** [comment]
https://github.com/user-attachments/assets/63fa6fcd-cd15-41b8-be3f-70a13e21ca31

This is the current demo. There is a lot of scope for further development.

**Pull request merged**
